### ISSUE TITLE
[fedora-x86_64] Compile error v1.7_beta1

### ISSUE THREAD

**Issue by AkiraNorthstar** [beandog/dvd_info#1]
HI!,
When i try to compile dvd_info [(commit)](https://github.com/beandog/dvd_info/commit/55f73b5ebdac038461ad2656952530d670bc386e) under fedora 31, i always get errors and the build will stop. Can you have a look there and give me a direction on how to fix it?
[dvd_info-compile-error.txt](https://github.com/beandog/dvd_info/files/4030971/dvd_info-compile-error.txt)
Thanks a lot!
Regrads,
Christian

**Comment by beandog** [comment]
Christian,

I haven't tested before on Fedora 31, I've got a VM setup now. Current tree should build okay, send me another output if it dies.

**Comment by beandog** [comment]
Okay so I used the CFLAGS you had in your export (don't know why they're getting set anyway), minus the redhat spec ones and here's what I got:

CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' ./configure

I cleaned up dvd_copy.c as well to be a bit safe for its string length on the filename, so it won't have any warnings there.

There are format-overflow warnings on dvd_backup, although they'll never trigger because the filename length of the DVD titles and its files will never exceed the variable size allotted. As long as you're not having your compiler exit on that warning, you should be good.

**Comment by beandog** [comment]
Okay, looked at it again, the actual error was dvd_backup wasn't building. It wasn't in the tree for a bit, but it's been fixed now anyway. You'll be good.
